# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rack'
gem 'sinatra'
gem 'pry'
gem 'recurl', path: '/Users/zaru/Sites/recurl'